version: '3.7'
services:
  app:
    image: test_sio/backend
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file:
      - ./.env
    volumes:
      - ./app:/app
      - ./docker/unit/config.json:/docker-entrypoint.d/unit.json
    ports:
      - ${APP_EXT_INTERFACE}:80
